### ISSUE TITLE
Spurious warnings with blead perl

### ISSUE THREAD

**Issue by leejo** [travis-perl/helpers#13]
If you look at https://travis-ci.org/leejo/cgi-fast/jobs/51777330 (line 85 onwards) you will see:

```
ERROR: The installation "blead" is unknown.
```

Yet the build seems to go on and run successfully against blead. Line 145 shows perl -V as reporting 5.21.10 and the build completes. I think there's perhaps some spurious warnings here, or an unnecessary step in the build?

FWIW the .travis.yml used here is https://github.com/leejo/cgi-fast/blob/master/.travis.yml

**Comment by haarg** [comment]
This is the expected behavior.  The initial switch that fails, and the version report after it are done by Travis-CI, with no way to avoid them.  The helper scripts then take over and build the correct perl as needed.

I'm hoping to talk to the Travis-CI developers soon about integrating at least part of the helper scripts to both improve the built in handling for perl projects, and fix this problem.

**Comment by leejo** [comment]
Thanks (next time i'll read the README!)
