### ISSUE TITLE
The dev target is not available

### ISSUE THREAD

**Issue by chocolateboy** [travis-perl/helpers#46]
The README mentions the `dev` target, but it results in an [error on Travis](https://travis-ci.org/chocolateboy/autobox/jobs/205898284):

```
$ perlbrew use dev

ERROR: The installation "dev" is unknown.
```

**Comment by chocolateboy** [comment]
Looks like `blead` [isn't working](https://travis-ci.org/chocolateboy/autobox/jobs/205902513) either ([cf.](https://github.com/SineSwiper/Dist-Zilla-TravisCI/issues/36)):

```
$ perlbrew use blead

ERROR: The installation "blead" is unknown.
```

**Comment by scottchiefbaker** [comment]
I'm getting a similar error... My [`.travis.yml`](https://github.com/scottchiefbaker/diff-so-fancy/blob/next/.travis.yml#L5) uses `dev` but when I try and run it I notice it points at a [URL](https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/14.04/x86_64/perl-dev.tar.bz2) on Amazonws that's a 404 error.

Ultimately the testing [continues](https://travis-ci.org/scottchiefbaker/diff-so-fancy/jobs/322621342), but it uses the default 5.14 instead of 5.27.x

**Comment by ribasushi** [comment]
@scottchiefbaker the linked build job ran under [`5.27.7`](https://travis-ci.org/scottchiefbaker/diff-so-fancy/jobs/322621342#L505-L506)

**Comment by kjetilk** [comment]
I tried this last night, and at first, it seemed to use 5.14, but then it did download the most recent 5.27. So, I guess it is not a bug, just something that needs documenting?

**Comment by haarg** [comment]
I'd certainly welcome improvements to the docs if you see a way to make this more obvious.
