### ISSUE TITLE
Perl 5.26

### ISSUE THREAD

**Issue by ylavoie** [travis-perl/helpers#50]
Please add to the list, for it was released as stable on Apr 30th, 2017

**Comment by wbraswell** [comment]
@ylavoie 
You can close this bug report, because Perl v5.26 is already supported natively by Travis, you do NOT need to use the Travis-Perl-Helpers in order to use Perl v5.26.  (However, you DO need Travis-Perl-Helpers for Perl v5.25 and likely others.)

You can see how v5.26 is included in my Travis config file here:
https://github.com/wbraswell/rperl/blob/master/.travis.yml
